#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Homebridge
# Starts the Homebridge daemon
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

# Wait for Avahi to become available
s6-svwait -u -t 5000 /var/run/s6/services/avahi

# Wait at least 5 seconds before staring Homebridge
# Avahi might need some time.
sleep 5

if hass.debug; then
  exec homebridge -D -U /config/homebridge/
else
  exec homebridge -U /config/homebridge/
fi
