#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Homebridge
# Starts the Homebridge daemon
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare -a homebridge_options

# Wait for Avahi to become available
s6-svwait -u -t 5000 /var/run/s6/services/avahi

# Wait at least 5 seconds before staring Homebridge
# Avahi might need some time.
sleep 5

homebridge_options+=(-U "/config/homebridge")

if hass.config.true 'insecure'; then
  homebridge_options+=(--insecure)
fi

if hass.debug; then
  homebridge_options+=(--debug)
fi

exec homebridge "${homebridge_options[@]}"
